name: jobizz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Style & Widgets
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  device_preview: ^1.2.0
  pinput: ^5.0.0

  # Controllers
  flutter_bloc: ^8.1.6
  provider: ^6.1.2

  # Network & Storage
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/country_codes/phone.json

  fonts:
    - family: Circular Std
      fonts:
        - asset: assets/fonts/circular-std-medium.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700